# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3c88ced9e18ab102b94c72b78eb1c209cd75abecfb17f7749574043a1e3557ab0ff74db0138d01ae679deeb606f7d2f0074e74f121d9f462c72cb8e75d1d6e37

test:
  secret_key_base: b7e816ef9211ed8836b4cfc3311283cf9b603989530dd8d214afe0fd7677559cc12a7a0f9f6231d2fb5afe5000e4fdb7ba626bbae528df50c55a3830340e6aaa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
